language: objective-c

osx_image: xcode7.3

install:
  - mkdir -p /Users/travis/build/piotrdubiel/.nvm
  - export NVM_DIR="/Users/travis/build/piotrdubiel/.nvm"
  - brew install nvm
  - source $(brew --prefix nvm)/nvm.sh
  - nvm install 4.4.3
  - npm config set spin=false
  - npm config set progress=false
  - npm install

script:
  - npm run lint
